# -*- coding: utf-8 -*-
"""infytqassignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sVS4uapSwfNATPe00p2WZtc3V_H-aH_s

# 3.Jack and his three friends have decided to go for a trip by sharing the expenses of the fuel equally.

Write a Python program to calculate the amount (in Rs) each of them need to put in for the complete (both to and fro) journey.
The program should also display True, if the amount to be paid by each person is divisible by 5, otherwise it should display False. (Hint: Use the relational operators in print statement.)

Assume that mileage of the vehicle, amount per litre of fuel and distance for one way are given.
"""

#PF-Assgn-3
#This verification is based on string match.

mileage=12
amount_per_litre=40
distance_one_way=190
per_head_cost=0
divisible_by_five=False

#Start writing your code from here
#Populate the variables: per_head_cost and divisible_by_five

cost=(distance_one_way*2/12)*amount_per_litre
per_head_cost=cost/4
if(per_head_cost %5 ==0):
    divisible_by_five=True
else:
    divisible_by_five=False

#Do not modify the below print statements for verification to work
print(per_head_cost)
print(divisible_by_five)

"""4.Write a Python program to calculate and display the interest on a loan amount (Rupees) using the formula:
interest=(principal * rate of interest * time)/100

Test your code by using the given sample inputs.
Verify your code by using the 2nd sample input(highlighted) given below:

"""

#PF-Assgn-4
#This verification is based on string match.

principal=7800
rate_of_interest=7.7
time=26
interest=0

#Start writing your code from here
#Populate the variable: interest

i=principal*rate_of_interest*time
interest=i/100

#Do not modify the below print statement for verification to work
print(interest)

"""5.Write a pseudo-code to find out if a given year is a leap year or not.20 min
Any year which is divisible by 4 and not by 100 are leap years. Otherwise, any year which is divisible by 400 is also a leap year.
Use the drag and drop option provided to create the correct pseudo-code.

ANS:
input Year
if(Year%4==0 and Year%100!=0) then
display "It is a leap year"
else if(Year%400==0) then
display "It is a leap year"
else
display "It is not a leap year"
end-if

6.Write a pseudo-code to check whether a given number is a palindrome.
Examples of palindrome: 121, 1331, 2332,78900987,123456654321 etc.

ANS:
input Number
Temp=Number
Reverse=0
while(Number!=0) do
Remainder=Number%10
Reverse=Reverse*10+Remainder
Number=Number/10
end-while
if(Temp==Reverse) then
display "Palindrome"
else
display "Not a Palindrome"
end-if

13.Write a pseudo-code which helps ( O> ) to reach ( E ).
ANS:
Pseudo-code:
while(start != end) do

move forward

if(Right_Turn_Available) then

Turn 
Right

end-if

if(Red_Key_Found) then

Unlock Red Lock

else if(Blue_Key_Found) then

Unlock Blue Lock

end-if

end-while
"""